NYCT article basic positioning
SamanAtashi/NYCT_articles_2.0 pull request #1
Opened 2021-03-29 10:14 UTC by SamanAtashi

NYCT article is a clone of the actual [wensite](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0).

Features that have been used in this project include:
1. basic html/css structure
2. positioning element using tools such as (flex, position)

2021-03-30 13:08 UTC, ElijahTobs requested changes
# Status: Changes Required :recycle: 

## Hi @SamanAtashi :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there's still a little more to be done before this milestone can be approved.

## REQUIRED

* [ ] Elements on your page should be aligned with a combination of all three techniques ([float](https://css-tricks.com/all-about-floats/), [flex](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) and [grid](https://css-tricks.com/snippets/css/complete-guide-grid/)). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_pathwright.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538403/)) and ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/positioning_and_floating_elements/flex_float_grid_requirement_odin.png) from [Odin](https://www.theodinproject.com/courses/html5-and-css3/lessons/positioning-and-floating-elements#introduction)). You didn't make use of float and grid. Kindly see to that.
* [ ] Kindly get rid of the horizontal scroll bar at the bottom of your page. 

> ### "As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561#) you have 2 code reviews left for this project."

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

2021-03-30 14:31 UTC, SamanAtashi commented
> @Elijah Ayandokun

Thank you for the feedback.
I added grid and float to the project but I can not find horizontal scrollbar.
Could you send me a screenshot or a guide regarding this issue?

2021-03-31 06:06 UTC, Berabjesus approved these changes
# **Status: PROJECT APPROVED** 
#### Excellent job on this project [@SamanAtashi](https://github.com/SamanAtashi). :fireworks: Keep it up.  :champagne: :champagne: 
#### The [clone](https://samanatashi.github.io/NYCT_articles_2.0/) shows a good understanding and usage of Bootstrap. :100:##- The cloned page looks as it should and meets all the project specifications.
- The project has a descriptive README.md and is professionally done.
- Pull Request has a meaningful title and description.
- No linter errors
- Excellent semantic HTML 👏 
- The repo has followed all the guidelines there are to follow (GitHub flow etc.)
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete. 👍** 
Before you merge to the main branch please have a look at the following optional comments.
- [ ] [optional] Please remove commented piece of codes. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [ ] [Optional] Avoid duplicate usage of rules, instead create one class for a rule and use it on the HTML. (For example, `display: flex` is used 36 times in the CSS, instead create a class for it, for example, `d-flex` and use that class in the HTML)

I wish you all the very best in your next tasks:1st_place_medal:
#### **If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**HAPPY CODING :computer:**[Bereket Beshane](https://bereketababu.me)** | [LinkedIn](linkedin.com/in/bereketbeshane) | [GitHub](https://github.com/Berabjesus)

2021-03-31 06:06 UTC, Berabjesus commented on style.css
> +} */
- [ ] [optional] Please remove commented piece of codes. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2021-03-31 06:06 UTC, Berabjesus commented on style.css
> +} */
- [ ] [optional] Please remove commented piece of codes. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2021-03-31 06:06 UTC, Berabjesus commented on style.css
> +} */
- [ ] [optional] Please remove commented piece of codes. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2021-03-31 06:06 UTC, Berabjesus commented on style.css
> +/* .box-2 .small-box .row-1-small-pic button img { */
- [ ] [optional] Please remove commented piece of codes. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2021-03-31 06:06 UTC, Berabjesus commented on style.css
> +}
- [ ] [optional] Please remove commented piece of codes. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2021-03-31 06:06 UTC, Berabjesus commented on style.css
> +	text-decoration: underline;
- [ ] [optional] Please remove commented piece of codes. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

2021-03-31 06:23 UTC, SamanAtashi commented
Thanks a lot, man. that really helped. 🙏

2021-03-31 06:26 UTC, merged

2021-03-31 07:03 UTC, Berabjesus commented
> Thanks a lot, man. that really helped. 🙏

You are welcome. 👍 
For future reference, don't delete the branches after working on them in case you have to make further changes. (personal opinion)